version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_account
    ports:
      - "5432:5432"
